version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on: 
      - wordpress
        # condition: service_healthy
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/wordpress/
    networks:
      - common
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env
    networks:
      - common
    ports:
      - 3306:3306

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/wordpress/
    networks:
      - common
    ports:
      - 9000:9000

networks:
  common:
    driver: bridge

volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pcazac/data/files_db

  WordPress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pcazac/data/files_wordpress